import test from 'node:test';
import assert from 'node:assert/strict';
import {purchaseTiming} from '../server/purchase-dates.js';
import {mapTransactions} from '../server/bank.js';
import {validateImport,mergePurchaseDates,displayPurchaseDates} from '../dist/core.js';
import {groupTransactions,sum} from '../dist/periods.js';
const row={status:'BOOK',credit_debit_indicator:'DBIT',transaction_amount:{amount:'12.80',currency:'EUR'},booking_date:'2026-10-08',entry_reference:'purchase-1',creditor:{name:'Marché'}};
test('a Wednesday purchase stays on Wednesday even when booked Thursday',()=>{const t=mapTransactions([{...row,transaction_date:'2026-10-07'}],'account');assert.equal(sum(groupTransactions(t,'2026-10-07','day').visible),1280);assert.equal(sum(groupTransactions(t,'2026-10-08','day').visible),0);assert.equal(t[0].bookingDate,'2026-10-08')});
test('explicit card-label dates are parsed, validated and bounded; bank purchase date has priority',()=>{for(const label of ['FACTURE CARTE DU 071026 MARCHE','PAIEMENT CB DU 07/10/2026 MARCHE','ACHAT CARTE LE 07.10.26'])assert.deepEqual(purchaseTiming({...row,remittance_information:[label]}),{date:'2026-10-07',bookingDate:'2026-10-08',dateBasis:'label'});assert.equal(purchaseTiming({...row,transaction_date:'2026-10-06',remittance_information:['FACTURE CARTE DU 071026']}).date,'2026-10-06');for(const label of ['FACTURE CARTE DU 310926','FACTURE CARTE DU 091026','REFERENCE 071026','VIREMENT DU 071026','FACTURE CARTE DU 071026 FACTURE CARTE DU 061026'])assert.equal(purchaseTiming({...row,remittance_information:[label]}).date,null)});
test('booking-only transactions stay undated and accessible without contributing to daily totals',()=>{const t=validateImport({version:1,transactions:mapTransactions([row],'account')});assert.equal(t.length,1);assert.equal(t[0].date,null);assert.equal(t[0].bookingDate,'2026-10-08');assert.equal(t[0].dateBasis,'unknown');for(const mode of ['day','week','month'])assert.equal(groupTransactions(t,'2026-10-08',mode).visible.length,0)});
test('pending purchase dates survive bookkeeping when an identical bank reference exists',()=>{const pending=mapTransactions([{...row,status:'PDNG',transaction_date:'2026-10-07'}],'account'),booked=mapTransactions([row],'account');assert.equal(pending[0].id,booked[0].id);assert.equal(mergePurchaseDates(booked,pending)[0].date,'2026-10-07');const both=mapTransactions([row,{...row,status:'PDNG',transaction_date:'2026-10-07'}],'account');assert.equal(both.length,1);assert.equal(both[0].date,'2026-10-07');assert.equal(both[0].status,'booked');assert.equal(mergePurchaseDates([{...booked[0],id:'unrelated'}],pending)[0].date,null)});

test('an undated received purchase remains visible with an explicitly estimated accounting day',()=>{const original=mapTransactions([row],'account'),displayed=displayPurchaseDates(original);assert.equal(original[0].date,null);assert.equal(displayed[0].dateBasis,'estimated');assert.equal(sum(groupTransactions(displayed,'2026-10-08','day').visible),1280)});
