import {classifyTransaction} from './classification.js';
import {purchaseTiming} from './purchase-dates.js';
import {createPrivateKey,createHash,sign,randomBytes,createCipheriv,createDecipheriv,timingSafeEqual} from 'node:crypto';
export const ORIGIN='https://money-bubble-theo.vercel.app';
const APP_ID='361704f1-6efa-465b-9f90-0b00b6693c4e';
export class BankError extends Error{constructor(code,status=400){super(code);this.code=code;this.status=status}}
export function privateKey(){try{const pem=process.env.ENABLE_BANKING_PRIVATE_KEY?.replaceAll('\\n','\n');if(!pem)throw Error();const key=createPrivateKey(pem);if(key.asymmetricKeyType!=='rsa')throw Error();return key}catch{throw new BankError('configuration',503)}}
function cookieKey(){return createHash('sha256').update('money-bubble-cookie-v1\0').update(privateKey().export({type:'pkcs8',format:'der'})).digest()}
export function seal(value,purpose){const iv=randomBytes(12),c=createCipheriv('aes-256-gcm',cookieKey(),iv);c.setAAD(Buffer.from(purpose));const ciphertext=Buffer.concat([c.update(JSON.stringify(value)),c.final()]);return Buffer.concat([iv,c.getAuthTag(),ciphertext]).toString('base64url')}
export function unseal(raw,purpose){try{if(!raw||raw.length>3800)return null;const b=Buffer.from(raw,'base64url');const c=createDecipheriv('aes-256-gcm',cookieKey(),b.subarray(0,12));c.setAAD(Buffer.from(purpose));c.setAuthTag(b.subarray(12,28));const value=JSON.parse(Buffer.concat([c.update(b.subarray(28)),c.final()]).toString());if(!Number.isFinite(value.exp)||value.exp<Date.now()/1000)return null;return value}catch{return null}}
export function cookie(req,name){return (req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith(name+'='))?.slice(name.length+1)}
export function setCookie(res,name,value,age){const existing=res.getHeader('Set-Cookie')||[];res.setHeader('Set-Cookie',[...(Array.isArray(existing)?existing:[existing]),`${name}=${value}; Path=/; HttpOnly; Secure; SameSite=Lax; Max-Age=${Math.max(0,Math.floor(age))}`])}
export function guard(req,res,method){res.setHeader('Cache-Control','no-store');res.setHeader('Referrer-Policy','no-referrer');res.setHeader('X-Content-Type-Options','nosniff');if(req.method!==method)throw new BankError('method',405);if(method==='POST'&&req.headers.origin!==ORIGIN)throw new BankError('origin',403);const host=req.headers.host;if(host!==new URL(ORIGIN).host)throw new BankError('host',403)}
export function session(req){const s=unseal(cookie(req,'__Host-mb-bank'),'bank-session');if(!s||typeof s.sid!=='string'||!Array.isArray(s.accounts)||!s.accounts.length)throw new BankError('reconnect',401);return s}
export function same(a,b){return typeof a==='string'&&typeof b==='string'&&Buffer.byteLength(a)===Buffer.byteLength(b)&&timingSafeEqual(Buffer.from(a),Buffer.from(b))}
export function jwt(){const key=privateKey(),now=Math.floor(Date.now()/1000),enc=x=>Buffer.from(JSON.stringify(x)).toString('base64url');const body=enc({typ:'JWT',alg:'RS256',kid:process.env.ENABLE_BANKING_APP_ID||APP_ID})+'.'+enc({iss:'enablebanking.com',aud:'api.enablebanking.com',iat:now,exp:now+300});return body+'.'+sign('RSA-SHA256',Buffer.from(body),key).toString('base64url')}
export async function api(path,{method='GET',body,req,fetcher=fetch,timeoutMs=18000}={}){const headers={Authorization:'Bearer '+jwt(),Accept:'application/json'};if(body)headers['Content-Type']='application/json';if(req){const mappings={'user-agent':'Psu-User-Agent',accept:'Psu-Accept','accept-language':'Psu-Accept-Language','accept-encoding':'Psu-Accept-Encoding'};for(const [k,v]of Object.entries(mappings))if(req.headers[k])headers[v]=req.headers[k];const ip=req.headers['x-real-ip']||req.headers['x-forwarded-for']?.split(',')[0]?.trim();if(ip)headers['Psu-Ip-Address']=ip;headers['Psu-Referer']=ORIGIN+'/';headers['Psu-Accept-Charset']='utf-8'}let response;try{response=await fetcher('https://api.enablebanking.com'+path,{method,headers,body:body?JSON.stringify(body):undefined,signal:AbortSignal.timeout(timeoutMs),redirect:'error'})}catch{throw new BankError('unavailable',502)}const data=await response.json().catch(()=>({}));if(!response.ok){const code=String(data.error||data.code||'');console.warn('Enable Banking API error',{status:response.status,code:/^[A-Z_]{1,80}$/.test(code)?code:'UNKNOWN'});if(response.status===429)throw new BankError('rate_limit',429);if(/EXPIREDSESSION|INVALIDSESSION|SESSION_EXPIRED|EXPIRED_SESSION|REVOKED_SESSION|CLOSED_SESSION|SESSION_DOES_NOT_EXIST/.test(code))throw new BankError('reconnect',401);if(/APPLICATION.*(INACTIVE|NOT_ACTIVE)|APPLICATION_NOT_FOUND|INVALID_SIGNATURE|UNAUTHORIZED/.test(code)||response.status===401)throw new BankError('provider_configuration',503);throw new BankError('bank_unavailable',502)}return data}
export function failure(res,error){res.status(error instanceof BankError?error.status:500).json({error:error instanceof BankError?error.code:'unavailable'})}
export function decimalCents(input){if(typeof input!=='string'||!/^[-+]?\d+(\.\d{1,2})?$/.test(input))throw Error('Invalid money');const negative=input.startsWith('-');const [whole,fraction='']=input.replace(/^[-+]/,'').split('.');const n=Number(whole)*100+Number(fraction.padEnd(2,'0'));if(!Number.isSafeInteger(n)||n>100000000)throw Error('Invalid money');return negative?-n:n}
export function mapTransactions(rows,account){const occurrences=new Map(),refs=new Set(),result=[],knownDates=new Map();for(const r of rows){if(!r.entry_reference||r.credit_debit_indicator!=='DBIT'||r.transaction_amount?.currency!=='EUR'||!['BOOK','PDNG'].includes(r.status))continue;const timing=purchaseTiming(r);if(!timing.date)continue;if(!knownDates.has(r.entry_reference))knownDates.set(r.entry_reference,timing);else if(knownDates.get(r.entry_reference)?.date!==timing.date)knownDates.set(r.entry_reference,null);}for(const t of [...rows].sort((a,b)=>(a.status==='BOOK'?0:1)-(b.status==='BOOK'?0:1))){if(t.credit_debit_indicator!=='DBIT'||t.transaction_amount?.currency!=='EUR'||!['BOOK','PDNG'].includes(t.status))continue;let cents;try{cents=Math.abs(decimalCents(t.transaction_amount.amount))}catch{continue}if(!cents)continue;let {date,bookingDate,dateBasis}=purchaseTiming(t);const known=knownDates.get(t.entry_reference);if(!date&&known){date=known.date;dateBasis=known.dateBasis}const identityDate=t._identity_date??(t.transaction_date||t.booking_date||'').slice(0,10);const merchant=String(t.creditor?.name||t.remittance_information?.join(' ')||t.bank_transaction_code?.description||'Dépense').slice(0,200);const ref=t.entry_reference?String(t.entry_reference):null;const base=ref?'ref:'+ref:(t.status==='PDNG'?'pending:':'')+JSON.stringify([identityDate,t.booking_date,cents,merchant,t.bank_transaction_code]);if(ref&&refs.has(ref))continue;if(ref)refs.add(ref);const nth=occurrences.get(base)||0;occurrences.set(base,nth+1);const id='bank-'+createHash('sha256').update(account+'\0'+base+'\0'+(ref?0:nth)).digest('hex').slice(0,40);const classification=classifyTransaction(t);result.push({id,date,bookingDate,merchant,amountCents:cents,...classification,status:t.status==='PDNG'?'pending':'booked',dateBasis})}return result}
export function selectBalance(rows){for(const type of ['ITAV','CLAV','ITBD','CLBD']){const b=rows.find(b=>b.balance_type===type&&b.balance_amount?.currency==='EUR');if(b){try{return {amount:decimalCents(b.balance_amount.amount),type,available:['ITAV','CLAV'].includes(type),asOf:b.reference_date||null}}catch{}}}return null}
